# Generated by Django 5.1.6 on 2025-03-10 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catogery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catogery_name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('desc', models.TextField(blank=True, max_length=200)),
                ('cat_img', models.ImageField(blank=True, upload_to='photos/catogeries')),
            ],
            options={
                'verbose_name': 'catogery',
                'verbose_name_plural': 'catogeries',
            },
        ),
    ]
